# Generated by Django 4.2.4 on 2023-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_proifle_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_picture'),
        ),
    ]
