# Generated by Django 4.2.4 on 2023-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://img.freepik.com/free-vector/fast-food-black-background-poster_1284-14589.jpg?w=2000', max_length=500),
        ),
    ]
